### ISSUE TITLE
orfeo-ice fails to build on 10.7.5

### ISSUE THREAD

**Issue by raughter** [OSGeo/homebrew-osgeo4mac#67]
Here is the gist:
https://gist.github.com/811bc97790d2cd698df9

Here is what appears to be the juicy bit:
CMakeFiles/otbiceviewer.dir/otbIceViewer.cxx.o -c /tmp/orfeo-ice-h8FwMW/Ice-bde0f85ca45d/Application/otbIceViewer.cxx
In file included from /tmp/orfeo-ice-h8FwMW/Ice-bde0f85ca45d/Application/otbIce.cxx:18:
/tmp/orfeo-ice-h8FwMW/Ice-bde0f85ca45d/Application/otbIceViewer.h:37:10: fatal error: 'GL/freeglut.h' file not found
In file included from /tmp/orfeo-ice-h8FwMW/Ice-bde0f85ca45d/Application/otbIceViewer.cxx:18:
/tmp/orfeo-ice-h8FwMW/Ice-bde0f85ca45d/Application/otbIceViewer.h:37:10: fatal error: 'GL/freeglut.h' file not found
