### ISSUE TITLE
orfeo5 fails to compile

### ISSUE THREAD

**Issue by grgurev** [OSGeo/homebrew-osgeo4mac#182]
Hello, 
please could anyone help why orfeo is not compiling.
Install line is`brew install orfeo5`and gist-logs are [here](https://gist.github.com/anonymous/93c9e7a278f1e896b3ae6068696c1d97)

**Comment by dakcarto** [comment]
@grgurev thanks for reporting!

Hmm, this sure doesn't look right:

```
make[2]: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenCL.framework', needed by `lib/libOTBCommon-5.4.1.dylib'.  Stop.
```

Will investigate when I have a 10.12 dev environ set up. Still working on 10.11.6 with latest Xcode 7.3.1.

**Comment by pat-s** [comment]
I got the following error log:

```ruby
brew install orfeo5
==> Installing orfeo5 from osgeo/osgeo4mac
==> Installing dependencies for osgeo/osgeo4mac/orfeo5: ossim, tinyxml, muparser, libkml, libsvm, minizip
==> Installing osgeo/osgeo4mac/orfeo5 dependency: ossim
==> Cloning https://github.com/ossimlabs/ossim.git
Cloning into '/Users/pjs/Library/Caches/Homebrew/ossim--git'...
remote: Counting objects: 2360, done.
remote: Compressing objects: 100% (2042/2042), done.
remote: Total 2360 (delta 424), reused 1765 (delta 308), pack-reused 0
Receiving objects: 100% (2360/2360), 7.08 MiB | 6.06 MiB/s, done.
Resolving deltas: 100% (424/424), done.
==> Checking out branch master
==> cmake ../ossim/cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/ossim/1.9.0_1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DOSSIM_DEV_HOME=/private/tmp/
==> make
Last 15 lines from /Users/pjs/Library/Logs/Homebrew/ossim/02.make:
                          ^
/usr/local/include/geos/geom/GeometryFactory.h:464:2: note: declared protected here
        GeometryFactory(const PrecisionModel* pm, int newSRID);
        ^
/tmp/ossim-20170202-96230-2o725/ossim/src/base/ossimPolyArea2d.cpp:42:68: error: calling a protected destructor of class 'geos::geom::GeometryFactory'
   virtual ~ossimGeometryFactoryWrapper(){if(m_geomFactory) delete m_geomFactory;m_geomFactory=0;}
                                                                   ^
/usr/local/include/geos/geom/GeometryFactory.h:474:10: note: declared protected here
        virtual ~GeometryFactory();
                ^
2 errors generated.
make[2]: *** [ossim/src/CMakeFiles/ossim.dir/base/ossimPolyArea2d.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [ossim/src/CMakeFiles/ossim.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by dakcarto** [comment]
@grgurev, @pat-s thanks for reporting. Looks like OSSIM is not compatible with latest GEOS update. I will look into whether latest commits upstream at the OSSIM project build (seems to be some work to address this maybe).
