### ISSUE TITLE
brew tap not working on macOS 12.2.1

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/homebrew-osgeo4mac#1421]
**Please answers the following**

I've... 
- I read
	- [x] the [reporting issues](https://osgeo.github.io/homebrew-osgeo4mac/docs/reporting-issues/)
	- [x] the [troubleshooting](https://osgeo.github.io/homebrew-osgeo4mac/docs/troubleshooting/)
- [x] I checked the documentation and found no answer
- [ ] I tried to install after following the suggestions
- [ ] I am running the latest version (`brew update` twice?)
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I uploaded logs: `brew gist-logs formula`

**Describe the bug**

Visiting [readme.md](https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/README.md) instructions:

> Just ``brew tap osgeo/osgeo4mac`` and then ``brew install <formula>``. Easy, isn't it?

The first step ``brew tap osgeo/osgeo4mac`` fails with many invalid formula etc...

**To Reproduce**

1. Go to '[README.md](https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/README.md)'
2. Follow instructions to ``brew tap osgeo/osgeo4mac``
3. See error

```
Resolving deltas: 100% (9469/9469), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/osgeo-vtk.rb
osgeo-vtk: Invalid bottle tag symbol
..
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/osgeo-postgis@2.4.rb
osgeo-postgis@2.4: undefined method `cellar' for #<BottleSpecification:0x00007ff5e89bc270>
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/osgeo-marble.rb
osgeo-marble: Invalid bottle tag symbol
Error: Cannot tap osgeo/osgeo4mac: invalid syntax in tap!
```

**Expected behavior**

Expected to see osgeo added to list for ``brew tap``.

**Additional context**

`brew doctor` output: 

```shell
Your system is ready to brew.
```

`brew config` output:
```
HOMEBREW_VERSION: 3.4.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: ea0ddc3297739b7380887d4a7e6b6590c314dca9
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 16dd6d43d12cc3a77ae90cd4712b33e3d745fe39
Core tap last commit: 37 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: /usr/bin/pico
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.35.1 => /usr/local/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.2.1-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
```

**Logs**

[logs](https://gist.github.com/jodygarnett/a499c351f34776cf6c4a5ab56efae4e2)

**Comment by jodygarnett** [comment]
This ticket has not had a response from a developer; there is no reason for a stale bot to clean it up.

**Comment by anthony-chadwick** [comment]
Having the same exact errors here as well. Your config is basically identical to mine as well.

**Comment by pramock4bs** [comment]
@jodygarnett Facing the same issue, any update or workaround?

**Comment by jodygarnett** [comment]
No response so far, I think I was focused on troubleshooting a geosever configuration and had to switch over to a linux docker image.

**Comment by jodygarnett** [comment]
Looks to be related to https://github.com/OSGeo/homebrew-osgeo4mac/issues/1410

I expect brew changed something and these bottles need to be updated

**Comment by jodygarnett** [comment]
Looking up for other examples of the error message and I found https://github.com/Homebrew/discussions/discussions/2429

> The syntax of the formula you're trying to install is too old to work with the installed version of brew. You can remove the bottle do block and see if you get any further.

So yeah this issue has been reported for a number of years with no action; I would consider this project inactive.

**Comment by bhjolly** [comment]
> Looking up for other examples of the error message and I found [Homebrew/discussions#2429](https://github.com/orgs/Homebrew/discussions/2429)
> 
> > The syntax of the formula you're trying to install is too old to work with the installed version of brew. You can remove the bottle do block and see if you get any further.
> 
> So yeah this issue has been reported for a number of years with no action; I would consider this project inactive.

Well that's disappointing....
